server:
  port: 8085
  servlet:
    context-path: /user-process-management

form-management-provider:
  url: http://localhost:8084

bpms:
  url: http://localhost:8080

ceph:
  http-endpoint: http://localhost:8100
  access-key: access-key
  secret-key: secret-key
  bucket: bucket

s3:
  config:
    client:
      protocol: http
    options:
      pathStyleAccess: true
