bpms:
  url: http://localhost:8800

storage:
  form-data:
    type: redis
  backend:
    redis:
      sentinel:
        master: mymaster
        nodes: 127.0.0.1:26379
    ceph:
      http-endpoint: http://localhost:8100
      access-key: access-key
      secret-key: secret-key
      bucket: bucket

form-submission-validation:
  url: http://localhost:8083

s3:
  config:
    client:
      protocol: http
    options:
      pathStyleAccess: true

token:
  name: x-access-token
  value-with-role-officer: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGWU1uVjA0bFdCTjhYc2k\
  5SkZqRDlLWmFlTXBSZm51X054N1E5bEpPa2ZjIn0.eyJqdGkiOiJlN2JmNDZkOS04MTU3LTQ0YTctOTA2NS1lZDg3OTJmOGVj\
  ZWEiLCJleHAiOjE2MTgzMTY3MjUsIm5iZiI6MCwiaWF0IjoxNjE4MzE2NDI1LCJpc3MiOiJodHRwczovL3BsYXRmb3JtLWtle\
  WNsb2FrLmFwcHMuY2ljZDIubWR0dS1kZG0ucHJvamVjdHMuZXBhbS5jb20vYXV0aC9yZWFsbXMvbWR0dS1kZG0tZWRwLWNpY2\
  QtbG93Y29kZS1kZXYtZGV2LW9mZmljZXItcG9ydGFsIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjcwMDRlYmRlLTY4Y2YtNGU\
  yNS1iYjc2LWIxNjQyYTM4MTRlNSIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9mZmljZXItcG9ydGFsIiwiYXV0aF90aW1lIjow\
  LCJzZXNzaW9uX3N0YXRlIjoiZGZlNjU1YjAtNzA1MS00NDYzLTg0ZDQtOTY1OGQ5MjA3ZWEzIiwiYWNyIjoiMSIsImFsbG93Z\
  WQtb3JpZ2lucyI6WyJodHRwczovL29mZmljZXItcG9ydGFsLWxvd2NvZGUtZGV2LWRldi5hcHBzLmNpY2QyLm1kdHUtZGRtLn\
  Byb2plY3RzLmVwYW0uY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZpY2VyIiwib2ZmbGluZV9hY2Nlc3MiLCJ\
  kZXZlbG9wZXIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im9mZmljZXItcG9ydGFsIjp7InJv\
  bGVzIjpbIm9mZmljZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1sa\
  W5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInJlYWxtUm9sZXMiOlsib2ZmaWNlciIsIm\
  9mZmxpbmVfYWNjZXNzIiwiZGV2ZWxvcGVyIiwidW1hX2F1dGhvcml6YXRpb24iXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJ\
  yb2xlcyI6WyJvZmZpY2VyIl0sIm5hbWUiOiJ0ZXN0dXNlciB0ZXN0dXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3R1\
  c2VyIiwiZ2l2ZW5fbmFtZSI6InRlc3R1c2VyIiwiZmFtaWx5X25hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdHVzZXJAd\
  GVzdHVzZXIuY29tIn0.Ss8p2ehfIGPq7K6YS5mwpE_-OlAIgVyGb4dnch_9uaAMazA51ONIsfbFvb7ZPRHrA9z3NJ3FS_u7O0\
  JPCO7jclYQQJux6G7O4SCHf5EMZzO8BPxI0q6mWWwDH-jJAV5guMd3e8hiUZZ_NwcaEZywjDbD5q3r082cERSHnpoSVOAqfZE\
  LRjfeu6UsQZvzqhi5eMSCrxm7z88r5OEqAf__gxBPytvvlKK7-WiN555mZie80aJwrr7uA"
  value-with-role-citizen: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkZZTW5WMDRsV0JOOFhzaTlKRmp\
  EOUtaYWVNcFJmbnVfTng3UTlsSk9rZmMifQ.eyJqdGkiOiJlN2JmNDZkOS04MTU3LTQ0YTctOTA2NS1lZDg3OTJmOGVjZWEiL\
  CJleHAiOjE2MTgzMTY3MjUsIm5iZiI6MCwiaWF0IjoxNjE4MzE2NDI1LCJpc3MiOiJodHRwczovL3BsYXRmb3JtLWtleWNsb2\
  FrLmFwcHMuY2ljZDIubWR0dS1kZG0ucHJvamVjdHMuZXBhbS5jb20vYXV0aC9yZWFsbXMvbWR0dS1kZG0tZWRwLWNpY2QtbG9\
  3Y29kZS1kZXYtZGV2LW9mZmljZXItcG9ydGFsIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjcwMDRlYmRlLTY4Y2YtNGUyNS1i\
  Yjc2LWIxNjQyYTM4MTRlNSIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9mZmljZXItcG9ydGFsIiwiYXV0aF90aW1lIjowLCJzZ\
  XNzaW9uX3N0YXRlIjoiZGZlNjU1YjAtNzA1MS00NDYzLTg0ZDQtOTY1OGQ5MjA3ZWEzIiwiYWNyIjoiMSIsImFsbG93ZWQtb3\
  JpZ2lucyI6WyJodHRwczovL29mZmljZXItcG9ydGFsLWxvd2NvZGUtZGV2LWRldi5hcHBzLmNpY2QyLm1kdHUtZGRtLnByb2p\
  lY3RzLmVwYW0uY29tIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJjaXRpemVuIiwib2ZmbGluZV9hY2Nlc3MiLCJkZXZl\
  bG9wZXIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im9mZmljZXItcG9ydGFsIjp7InJvbGVzI\
  jpbImNpdGl6ZW4iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcy\
  IsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInJlYWxtUm9sZXMiOlsiY2l0aXplbiIsIm9mZmx\
  pbmVfYWNjZXNzIiwiZGV2ZWxvcGVyIiwidW1hX2F1dGhvcml6YXRpb24iXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJyb2xl\
  cyI6WyJjaXRpemVuIl0sIm5hbWUiOiJ0ZXN0dXNlciB0ZXN0dXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3R1c2VyI\
  iwiZ2l2ZW5fbmFtZSI6InRlc3R1c2VyIiwiZmFtaWx5X25hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdHVzZXJAdGVzdH\
  VzZXIuY29tIn0.BmX7HJPwoY5LF1srPXTsvcnJ4LbqbJm4RyqXjsMXSN0"