apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  application.yml: |-
    bpms.url: http://bpms:8080
    ceph.http-endpoint: {{ .Values.ceph.host }}
    s3: {{ .Values.s3 | toYaml | nindent 6 }}
    form-management-provider.url: http://form-management-provider:3001
    server.max-http-header-size: 32KB
    {{- if eq .Values.deployProfile "dev" }}
    management.endpoints.web.exposure.include: '*'
    {{- end }}
    platform.security.csrf.enabled: {{ .Values.platform.security.csrf.enabled }}